
export default {
  hiraganaRowTitles: [
    'あ Row (A-O)',
    'か Row (KA-KO)',
    'さ Row (SA-SO)',
    'た Row (TA-TO)',
    'な Row (NA-NO)',
    'は Row (HA-HO)',
    'ま Row (MA-MO)',
    'や Row (YA-YO)',
    'ら Row (RA-RO)',
    'わ Row (WA-WO)',
    'ん Row (n/m)',
    'が Row (GA-GO)',
    'ざ Row (ZA-ZO)',
    'だ Row (DA-DO)',
    'ば Row (BA-BO)',
    'ぱ Row (PA-PO)',
    'きゃ Row (KYA-KYO)',
    'しゃ Row (SHA-SHO)',
    'ちゃ Row (CHA-CHO)',
    'にゃ Row (NYA-NYO)',
    'ひゃ Row (HYA-HYO)',
    'みゃ Row (MYA-MYO)',
    'りゃ Row (RYA-RYO)',
    'ぎゃ Row (GYA-GYO)',
    'じゃ Row (JA-JO)',
    'びゃ Row (BYA-BYO)',
    'ぴゃ Row (PYA-PYO)'
  ],
  katakanaRowTitles: [
    'ア Row (A-O)',
    'カ Row (KA-KO)',
    'サ Row (SA-SO)',
    'タ Row (TA-TO)',
    'ナ Row (NA-NO)',
    'ハ Row (HA-HO)',
    'マ Row (MA-MO)',
    'ヤ Row (YA-YO)',
    'ラ Row (RA-RO)',
    'ワ Row (WA-WO)',
    'ン Row (n/m)',
    'ガ Row (GA-GO)',
    'ザ Row (ZA-ZO)',
    'ダ Row (DA-DO)',
    'バ Row (BA-BO)',
    'パ Row (PA-PO)',
    'キャ Row (KYA-KYO)',
    'シャ Row (SHA-SHO)',
    'チャ Row (CHA-CHO)',
    'ニャ Row (NYA-NYO)',
    'ヒャ Row (HYA-HYO)',
    'ミャ Row (MYA-MYO)',
    'リャ Row (RYA-RYO)',
    'ギャ Row (GYA-GYO)',
    'ジャ Row (JA-JO)',
    'ビャ Row (BYA-BYO)',
    'ピャ Row (PYA-PYO)'
  ],
  kanaIndecies: [
    0,
    5,
    10,
    15,
    20,
    25,
    30,
    35,
    38,
    43,
    45,
    46,
    51,
    56,
    61,
    66,
    71,
    74,
    77,
    80,
    83,
    86,
    89,
    92,
    95,
    98,
    101
  ], 
}